name: Build QTBase for macOS
  
agent:
  type: Unity::VM::osx
  image: cds-ops/macos-10.14-perf:latest
  flavor: m1.mac

artifacts:
  qtbase-macos.zip:
    paths:
      - build/builds.7z

commands:
  - perl build.pl --arch=64

triggers:
  pushes:
    only:
      - qtbuild.5.13.2
