name: Build QTBase for Linux
  
agent:
  type: Unity::VM
  image: desktop/qt-linux-build-image:latest
  flavor: b1.xlarge

artifacts:
  qtbase-linux.zip:
    paths:
      - build/builds.7z

commands:
  - sudo sed -i -- 's/#deb-src/deb-src/g' /etc/apt/sources.list && sudo sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list
  - echo "Allowed source repositories"
  - sudo apt-get update -y
  - sudo apt-get upgrade -y
  - sudo apt-get install chrpath -y
  - sudo apt-get build-dep qt5-default -y
  - sudo apt-get install libxcb-xinerama0-dev
  - sudo apt-get install libx11-xcb-dev
  - sudo apt-get install libxkbcommon-dev
  - sudo apt-get install libssl-dev
  - cd /home/bokken/build/output/Unity-Technologies/qtbase
  - perl build.pl --arch=64

triggers:
  pushes:
    only:
      - qtbuild.5.13.2
      - qtbuild.5.13.2-linux
