name: Build QTBase for Linux
  
agent:
  type: Unity::VM
  image: desktop/qt-linux-build-image:latest
  flavor: b1.xlarge

artifacts:
  qtbase-linux-amd64:
    paths:
      - build/*.7z

commands:
  - git clone --branch OpenSSL_1_0_2-stable https://github.com/openssl/openssl
  - cp -f qt_attribution.json.openssl openssl/qt_attribution.json
  - sudo apt-get install -y qttools5-dev-tools libjson-perl
  - /usr/lib/qt5/bin/qtattributionsscanner --output-format json -o LICENSES.json.OVERRIDE .
  - sed -e "s|/home/bokken/build/output/Unity-Technologies/qtbase|/qtbase|g" LICENSES.json.OVERRIDE > /toolchains/linux/tmp/LICENSES.json.OVERRIDE
  - mkdir -p /toolchains/linux/usr/share/perl5/JSON/backportPP
  - cp /usr/share/perl5/JSON.pm /toolchains/linux/usr/share/perl5/
  - cp /usr/share/perl5/JSON/backportPP.pm /toolchains/linux/usr/share/perl5/JSON/
  - cp /usr/share/perl5/JSON/backportPP/Boolean.pm /toolchains/linux/usr/share/perl5/JSON/backportPP/
  - cp /usr/share/perl5/JSON/backportPP/Compat5005.pm /toolchains/linux/usr/share/perl5/JSON/backportPP/
  - cp /usr/share/perl5/JSON/backportPP/Compat5006.pm /toolchains/linux/usr/share/perl5/JSON/backportPP/
  - sudo mount --bind /dev /toolchains/linux/dev
  - mkdir /toolchains/linux/qtbase
  - sudo mount --bind /home/bokken/build/output/Unity-Technologies/qtbase /toolchains/linux/qtbase
  - sudo chroot --userspec=bokken:bokken /toolchains/linux sh -c "cd /qtbase ; perl build.pl --arch=64"

dependencies:
  - .yamato/create-source-artifact.yml

triggers:
  pushes:
    only:
      - qtbuild.5.9.7
