name: Build QTBase for macOS
  
agent:
  type: Unity::VM::osx
  image: slough-ops/macos-10.14-base
  flavor: m1.mac

artifacts:
  qtbase-macos-amd64:
    paths:
      - build/*.7z

commands:
  - |
    rm -rf ~/.cpan
    cpan config
    sudo cpan install JSON
    pushd ..
    wget https://public-stevedore.unity3d.com/r/public/7za-mac-x64/d42d7377392b_f3244e01c4f45f29f33d910dbaa747628d2f548bff6f436f83995739ac416620.zip
    unzip d42d7377392b_f3244e01c4f45f29f33d910dbaa747628d2f548bff6f436f83995739ac416620.zip
    wget https://artifactory.prd.it.unity3d.com/artifactory/stevedore-unity-internal/qtattrsscanner-mac-x64/5.15.2_b352b3970f63712d9221387b4ec1d6d2c1fb436877a507b92b64d6904caee90c.zip
    unzip 5.15.2_b352b3970f63712d9221387b4ec1d6d2c1fb436877a507b92b64d6904caee90c.zip
    popd
    PATH=$PATH:..:../bin
    perl build.pl --arch=64

dependencies:
  - .yamato/create-source-artifact.yml

triggers:
  pushes:
    only:
      - qtbuild.5.9.7
