name: Build QTBase for Linux
  
agent:
  type: Unity::VM
  image: desktop/qt-linux-build-image:latest
  flavor: b1.xlarge

artifacts:
  qtbase-linux.zip:
    paths:
      - build/builds.7z

commands:
  - git clone https://github.com/openssl/openssl
  - git -C /home/bokken/build/output/Unity-Technologies/qtbase/openssl checkout -b 1.0.2 origin/OpenSSL_1_0_2-stable
  - sudo mount --bind /dev /toolchains/linux/dev
  - mkdir /toolchains/linux/qtbase
  - sudo mount --bind /home/bokken/build/output/Unity-Technologies/qtbase /toolchains/linux/qtbase
  - sudo chroot --userspec=bokken:bokken /toolchains/linux sh -c "cd /qtbase ; perl build.pl --arch=64"

triggers:
  pushes:
    only:
      - qtbuild.5.9.7
